export * from './Search';
export * from './Bell';
export * from './Globe';
export * from './LogIn';
export * from './Trophy';
export * from './Star';
export * from './Cross';
export * from './Menu';
export * from './ThumbsUp';
export * from './ThumbsDown';
export * from './Share';
export * from './Gem';
export * from './Lock';
export * from './Coins';
export * from './Heart';
export * from './Message';
export * from './Trash';
export * from './Smile';
export * from './Sync';
export * from './ArrowUp';
export * from './CornerDownRight';
export * from './Video';
export * from './Calendar';
export * from './User';
export * from './Photo';
export * from './ArrowLeft';
export * from './Check';
export * from './Plus';
export * from './Settings';
export * from './Clock';
export * from './Mail';
export * from './Floppy';
export * from './Shield';
export * from './Copy';
export * from './Pencil';

// Aliases
export { Cross as X } from './Cross';
export { Message as MessageSquare } from './Message';
export { Trash as Trash2 } from './Trash';
export { Share as Share2 } from './Share';
export { Sync as Loader2 } from './Sync';
export { Sync as Loader } from './Sync';
export { Photo as ImageIcon } from './Photo';
export { Menu as MoreHorizontal } from './Menu';
export { Menu as MoreVertical } from './Menu';
export { Floppy as Save } from './Floppy';
export { Trophy as BarChart3 } from './Trophy';
export { Pencil as Edit } from './Pencil';
export { Shield as ShieldCheck } from './Shield';
